"""
Shared pipeline state object.

Every node in the LangGraph pipeline reads from and writes to this object.
Using Pydantic ensures all state transitions are type-safe and validated.

Design principle: state accumulates — each phase adds its output fields
without mutating previous fields. This makes the full trace inspectable.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

# ── Enums ────────────────────────────────────────────────────────────────────

class PipelineStatus(StrEnum):
    PENDING    = "pending"
    RUNNING    = "running"
    SUCCESS    = "success"
    FAILED     = "failed"
    CLARIFYING = "clarifying"   # waiting for user input
    RETRYING   = "retrying"


class ValidationStatus(StrEnum):
    PASS    = "pass"
    FAIL    = "fail"
    SKIPPED = "skipped"


# ── Sub-models ────────────────────────────────────────────────────────────────

class ColumnMeta(BaseModel):
    name: str
    data_type: str
    is_nullable: bool = True
    is_primary_key: bool = False


class TableMeta(BaseModel):
    name: str
    friendly_name: str = ""
    columns: list[ColumnMeta] = Field(default_factory=list)


class FKEdge(BaseModel):
    """A single foreign-key join relationship."""
    from_table: str
    from_column: str
    to_table: str
    to_column: str

    def as_join_hint(self) -> str:
        return (
            f"{self.from_table}.{self.from_column} "
            f"-> {self.to_table}.{self.to_column}"
        )


class ValidationResult(BaseModel):
    status: ValidationStatus = ValidationStatus.SKIPPED
    error_type: str | None = None        # maps to errors/types.py
    error_message: str | None = None
    details: dict[str, Any] = Field(default_factory=dict)


class RetryMeta(BaseModel):
    attempt: int = 0
    max_attempts: int = 3
    last_error: str | None = None

    @property
    def budget_exhausted(self) -> bool:
        return self.attempt >= self.max_attempts


class ObservabilityTrace(BaseModel):
    """Timing and token usage captured per node — exported to logs / OTEL."""
    node_timings: dict[str, float] = Field(default_factory=dict)   # node → seconds
    token_usage: dict[str, int] = Field(default_factory=dict)      # node → tokens
    retry_count: int = 0
    confidence_score: float | None = None   # 0.0–1.0 from A1


# ── Main shared state ─────────────────────────────────────────────────────────

class PipelineState(BaseModel):
    """
    The single shared state object that flows through every LangGraph node.

    Phases accumulate output into this object without overwriting prior fields:
      Phase 1  →  schema_full, schema_norm, name_mapping, fk_graph, fk_edges
      Phase 2  →  prompt_context, candidate_sql
      Phase 3  →  guardrail_result, validation_result
      Output   →  final_sql, final_report
    """

    # ── Input ─────────────────────────────────────────────────────────────────
    question: str = Field(..., description="Raw natural language question from user")
    db_connection_string: str = Field(
        ...,
        description="SQLAlchemy connection string — never logged or sent to LLM",
    )
    force_refresh: bool = Field(
        default=False,
        description="Set to True to bypass the schema cache and re-introspect the DB",
    )

    # ── Phase 1: Schema understanding ─────────────────────────────────────────
    schema_full: dict[str, Any] = Field(
        default_factory=dict,
        description="Raw schema metadata from T1 — tables, columns, types, PKs, FKs",
    )
    schema_norm: list[TableMeta] = Field(
        default_factory=list,
        description="Normalized schema with friendly names from T2",
    )
    name_mapping: dict[str, str] = Field(
        default_factory=dict,
        description="Friendly name → original DB name mapping from T2",
    )
    fk_graph: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Adjacency map of table relationships from T4",
    )
    fk_edges: list[FKEdge] = Field(
        default_factory=list,
        description="Flat list of FK join edges from T4",
    )

    # ── Phase 2: Contextualization & generation ───────────────────────────────
    prompt_context: str = Field(
        default="",
        description="Formatted system prompt built by T5",
    )
    candidate_sql: str = Field(
        default="",
        description="Raw SQL string generated by A1",
    )

    # ── Phase 3: Validation ───────────────────────────────────────────────────
    guardrail_result: ValidationResult = Field(
        default_factory=ValidationResult,
        description="Pass/fail from T6 regex + AST DML check",
    )
    validation_result: ValidationResult = Field(
        default_factory=ValidationResult,
        description="Structural validation result from T7 (sqlglot AST vs schema)",
    )

    # ── Retry & clarification ─────────────────────────────────────────────────
    retry_meta: RetryMeta = Field(default_factory=RetryMeta)
    clarification_question: str | None = Field(
        default=None,
        description="Question posed back to user when query is ambiguous",
    )
    clarification_answer: str | None = Field(
        default=None,
        description="User's answer to the clarification question",
    )

    # ── Output ────────────────────────────────────────────────────────────────
    final_sql: str | None = None
    final_report: dict[str, Any] = Field(default_factory=dict)

    # ── Pipeline metadata ─────────────────────────────────────────────────────
    status: PipelineStatus = PipelineStatus.PENDING
    trace: ObservabilityTrace = Field(default_factory=ObservabilityTrace)

    class Config:
        # Allow mutation — LangGraph nodes update state in place
        frozen = False
